apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facebook-ui
  template:
    metadata:
      labels:
        app: facebook-ui
    spec:
      containers:
      - name: facebook-ui
        image: busapooja/facebook-ui:latest
        ports:
        - containerPort: 80
